version: "3.8"

services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: opowiedzto-frontend-dev
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - api

  api:
    build:
      context: ./opowiedzto-api
      dockerfile: Dockerfile.dev
    container_name: opowiedzto-api-dev
    volumes:
      - ./opowiedzto-api:/app
      - /app/node_modules
      - ./opowiedzto-api/uploads/avatars:/app/uploads/avatars
    ports:
      - "3001:3001"
    env_file:
      - ./opowiedzto-api/.env
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=opowiedzto
    command: npm run start:dev

  db:
    image: postgres:16-alpine
    container_name: opowiedzto-db-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opowiedzto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: opowiedzto-pgadmin-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data_dev:
