services:
  db:
    image: postgres:16-alpine
    container_name: opowiedzto-db-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opowiedzto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d opowiedzto"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  api:
    build:
      context: ./opowiedzto-api
      dockerfile: Dockerfile.dev
    container_name: opowiedzto-api-dev
    volumes:
      - ./opowiedzto-api:/app
      - /app/node_modules
      - ./opowiedzto-api/uploads/avatars:/app/uploads/avatars
    ports:
      - "3001:3001"
    env_file:
      - ./opowiedzto-api/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: opowiedzto-frontend-dev
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - API_URL=http://api:3001
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: opowiedzto-pgadmin-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data_dev:
