FROM node:20-alpine

WORKDIR /app

# Kopiowanie plików konfiguracyjnych
COPY package*.json ./
COPY tsconfig*.json ./

# Instalacja zależności
RUN npm install

# Kopiowanie kodu źródłowego
COPY . .

# Ustawienie zmiennych środowiskowych
ENV NODE_ENV=development

# Uruchomienie aplikacji w trybie deweloperskim
CMD ["npm", "run", "start:dev"] 