name: Code Quality

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      check_type:
        description: "Typ sprawdzenia do uruchomienia"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - api
          - web

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache API dependencies
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.check_type == 'all' || inputs.check_type == 'api' }}
        uses: actions/cache@v4
        with:
          path: ./opowiedzto-api/node_modules
          key: ${{ runner.os }}-api-${{ hashFiles('opowiedzto-api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-api-

      - name: Cache Web dependencies
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.check_type == 'all' || inputs.check_type == 'web' }}
        uses: actions/cache@v4
        with:
          path: ./web/node_modules
          key: ${{ runner.os }}-web-${{ hashFiles('web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-web-

      - name: Install API dependencies
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.check_type == 'all' || inputs.check_type == 'api' }}
        working-directory: ./opowiedzto-api
        run: npm ci

      - name: Install Web dependencies
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.check_type == 'all' || inputs.check_type == 'web' }}
        working-directory: ./web
        run: npm ci --ignore-platform
        env:
          npm_config_target_platform: linux
          npm_config_target_arch: x64

      - name: Check API formatting
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.check_type == 'all' || inputs.check_type == 'api' }}
        working-directory: ./opowiedzto-api
        run: npm run format -- --check

      - name: Check Web formatting
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.check_type == 'all' || inputs.check_type == 'web' }}
        working-directory: ./web
        run: npm run format:check

      - name: Lint API code
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.check_type == 'all' || inputs.check_type == 'api' }}
        working-directory: ./opowiedzto-api
        run: npm run lint

      - name: Lint Web code
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.check_type == 'all' || inputs.check_type == 'web' }}
        working-directory: ./web
        run: npm run lint
