name: E2E Tests

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: opowiedzto_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            opowiedzto-api/package-lock.json
            web/package-lock.json

      - name: Install API dependencies
        working-directory: ./opowiedzto-api
        run: npm ci

      - name: Install Web dependencies
        working-directory: ./web
        run: npm ci

      - name: Build API
        working-directory: ./opowiedzto-api
        run: npm run build
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/opowiedzto_test

      - name: Run database migrations
        working-directory: ./opowiedzto-api
        run: npm run migration:run
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/opowiedzto_test

      - name: Build Web
        working-directory: ./web
        run: npm run build

      - name: Run E2E tests for API
        working-directory: ./opowiedzto-api
        run: npm run test:e2e
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/opowiedzto_test
