name: Unit Tests

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      test_type:
        description: "Typ testów do uruchomienia"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - backend
          - frontend
      run_coverage:
        description: "Uruchomić raporty pokrycia?"
        required: false
        default: true
        type: boolean

jobs:
  backend-tests:
    name: Backend Tests (API)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && (inputs.test_type == 'all' || inputs.test_type == 'backend') || github.event_name != 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache API dependencies
        uses: actions/cache@v4
        with:
          path: ./opowiedzto-api/node_modules
          key: ${{ runner.os }}-api-${{ hashFiles('opowiedzto-api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-api-

      - name: Install API dependencies
        working-directory: ./opowiedzto-api
        run: npm ci

      - name: Run linting
        working-directory: ./opowiedzto-api
        run: npm run lint

      - name: Run unit tests
        working-directory: ./opowiedzto-api
        run: npm run test:ci

      - name: Upload coverage reports
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_coverage == true }}
        uses: codecov/codecov-action@v4
        with:
          file: ./opowiedzto-api/coverage/lcov.info
          flags: backend
          name: backend-coverage

  frontend-tests:
    name: Frontend Tests (Web)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && (inputs.test_type == 'all' || inputs.test_type == 'frontend') || github.event_name != 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Web dependencies
        uses: actions/cache@v4
        with:
          path: ./web/node_modules
          key: ${{ runner.os }}-web-${{ hashFiles('web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-web-

      - name: Install Web dependencies
        working-directory: ./web
        run: npm ci

      - name: Run linting
        working-directory: ./web
        run: npm run lint

      - name: Run unit tests
        working-directory: ./web
        run: npm run test:ci

      - name: Upload coverage reports
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_coverage == true }}
        uses: codecov/codecov-action@v4
        with:
          file: ./web/coverage/lcov.info
          flags: frontend
          name: frontend-coverage

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]

    steps:
      - name: Check test results
        run: |
          echo "✅ All unit tests completed successfully!"
          echo "Backend tests: ${{ needs.backend-tests.result }}"
          echo "Frontend tests: ${{ needs.frontend-tests.result }}"
